export const users = [
  {
    id: "1",
    name: "Steve Rhodes",
    email: "steve@example.com",
    age: 36,
    isVerified: true,
  },
  {
    id: "2",
    name: "John Doe",
    email: "john@example.com",
    age: 28,
    isVerified: false,
  },
  {
    id: "3",
    name: "Jane Smith",
    email: "jane@example.com",
    age: 32,
    isVerified: true,
  },
  {
    id: "4",
    name: "Alice Johnson",
    email: "alice@example.com",
    age: 41,
    isVerified: true,
  },
  {
    id: "5",
    name: "Bob Williams",
    email: "bob@example.com",
    age: 25,
    isVerified: false,
  },
  {
    id: "6",
    name: "Charlie Brown",
    email: "charlie@example.com",
    age: 33,
    isVerified: true,
  },
  {
    id: "7",
    name: "Diana Prince",
    email: "diana@example.com",
    age: 29,
    isVerified: true,
  },
  {
    id: "8",
    name: "Ethan Hunt",
    email: "ethan@example.com",
    age: 45,
    isVerified: true,
  },
  {
    id: "9",
    name: "Fiona Gallagher",
    email: "fiona@example.com",
    age: 37,
    isVerified: false,
  },
  {
    id: "10",
    name: "George Costanza",
    email: "george@example.com",
    age: 52,
    isVerified: true,
  }
];